# Generated by Django 2.2.1 on 2019-06-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ispublished',
            field=models.BooleanField(default=False),
        ),
    ]
